### ISSUE TITLE
Cannot find types

### ISSUE THREAD

**Issue by Denny09310** [dutchigor/pluggable-electron#10]
### No types from node_modules

Hi, I don't know if I'm doing something wrong or it's a general thing. After installing the library, having seen from npm that it has built-in declarations for typescript I tried to import the module, but I am told that the types are not declared and to try to download @ types / pluggable-electron which however does not exists. My question is: can this library be used with typescript modules or should it be used with the classic require javascript and that's it?

**Comment by dutchigor** [comment]
Sorry for the late response. For anyone to who this is still relevant, I am using it with typescript for my own project successfully. Note that thi sis only available from version 0.4.3 though. If you are still facing the problem, do you have a repo I can look at to see what the problem might be?

**Comment by dutchigor** [comment]
Closing this since due to no response. Feel free to repoen if this is still an issue.
